### ISSUE TITLE
[BUG] Map selection incompatibility with some weapon mods

### ISSUE THREAD

**Issue by Yholl** [Mythotic-Tinker-Station/lexicon#22]
**Type of bug**
gamebreaking

**Map name**
VR

**Describe the bug**
Weapon mods such as LegenDoom and Final Doomer are incompatible with the VR map selection hubmap.
Playing on this map with these mods does not give you the votegun, and if you give yourself the votegun through the console, the votegun still does not have any effect. No existing weapons affect the map selections at all, making it impossible to use the vr map in any way.

**Expected behavior**
Maps should always be selectable by the player, perhaps even with a simpler backup method that will always work if the current votegun method does not.

**Comment by Tribeam** [comment]
In 156b86d you can now press use on screens as well as use the vote gun.

As for the incompatibility of the votegun, honestly i'm stump, because its just an invisible railshot that activates a "On Projectile Impact" line, nothing really should have any effect on that.

**Comment by Tribeam** [comment]
Well I'm gonna consider pressing 'Use' on the screens as a fix to this, even though its not a good one, it guarantees that players can vote if mods break the weapon, so gonna close the issue.

I spent hours trying to figure out a proper fix but I found nothing unfortunately, as far as I can tell this bug is some crazy anomaly.
