### ISSUE TITLE
[BUG] Doom 2 Redux level autocompletes itself

### ISSUE THREAD

**Issue by Mech-cyber** [Mythotic-Tinker-Station/lexicon#33]
**Type of bug**
Gamebreaking

**Mapset name**
Doom 2 Redux

**Map name**
RDX06

**Describe the bug**
Level just completes itself few seconds after its start.

**Expected behavior**
Game must not jump to stats screen, letting the player to play the level from start to finish instead.

**Screenshots**
![Screenshot_Doom_20200113_220846](https://user-images.githubusercontent.com/59827086/72269206-c3018c00-3655-11ea-9bd4-4329b4a1a947.png)
![Screenshot_Doom_20200113_220856](https://user-images.githubusercontent.com/59827086/72269208-c3018c00-3655-11ea-99bb-4192821b4f24.png)
![Безымянный](https://user-images.githubusercontent.com/59827086/72269209-c39a2280-3655-11ea-9762-510f38189ff6.png)

**To Reproduce (if Game Breaking)**
1. Load Lexicon with Demon Steele
2. When picking a character, choose Hae Lin
3. Choose "Doom 2 Redux" mappack
4. Play until the 6th map ("Crusher"), or warp there.
5. Go to the room adjacent to the one where you start and start running around or just stand still.
6. Few seconds later level ends with stats screen shown.

**Additional context**
Bug only appears if player chooses Hae Lin as playable character. It doesn't appear when Sun Shihong is chosen. Nothing happens when played without a mod.

**Comment by Tribeam** [comment]
Fixed in dfe789c

The issue with this map is that it's boom voodoo doll trickery was very specific about the player class's height/radius, depending on the default doom class, this was done for timing purposes.

I have modified the map to fix this however this does mess up the original timings of the effects.

For example the exit doors are delayed and the player can jump out of the exit elevator, but the map will still be exited regardless.

It is possible other redux maps might suffer from this issue

**Comment by Tribeam** [comment]
Gonna leave this open incase any other redux maps have similer issues, please report them here.

**Comment by Mech-cyber** [comment]
No problem similar to this one during the rest of the wad.

**Comment by Tribeam** [comment]
Then i shall claim victory over this issue and close it!
