### ISSUE TITLE
[REBUILD] Doom Core Trilogy needs testing!!!

### ISSUE THREAD

**Issue by mifu666** [Mythotic-Tinker-Station/lexicon#73]
Doom Core Trilogy was just re-added to the rebuild branch. This requires testing from the crack team of mapset testers.

Please add a note to the ticket if you are testing this and please report back on the following:

Any texture issues (missing or incorrect textures etc)

- Thing issues (incorrect decorations. monsters etc
- Show stopping bugs
- Any other issues

This should be tested within the week before the weekend with the other mapsets added.

**Comment by michael-is-qcde** [comment]
DCOR07 exit room has a missing texture BARONDED
![image](https://user-images.githubusercontent.com/57696110/80532012-b2d3a980-89c5-11ea-9ade-e67fc768d328.png)

_Dev note: Fixed in commit 3a79797_

**Comment by michael-is-qcde** [comment]
DCOR24: These switches in the same area appear to have wrong offsets.
![image](https://user-images.githubusercontent.com/57696110/80792996-09a4d300-8bc0-11ea-8c0e-8fc05f0ba94e.png)
![image](https://user-images.githubusercontent.com/57696110/80793406-3e655a00-8bc1-11ea-8448-c94d10b9949f.png)
![image](https://user-images.githubusercontent.com/57696110/80793617-cea39f00-8bc1-11ea-933b-2f1417d0edcf.png)
![image](https://user-images.githubusercontent.com/57696110/80793697-0579b500-8bc2-11ea-84ec-0d7891e4d47f.png)

_Dev note: Fixed in commit d5ca7f5_

**Comment by michael-is-qcde** [comment]
DCOR25: The same switch is back with a vengeance.
![image](https://user-images.githubusercontent.com/57696110/80795304-4f649a00-8bc6-11ea-9c8d-49985d043178.png)

_Dev note: Fixed in commit d5ca7f5_

**Comment by michael-is-qcde** [comment]
DCOR33: This elevator's texture in the first room is misaligned.
![image](https://user-images.githubusercontent.com/57696110/80797306-b59feb80-8bcb-11ea-8866-9bdeb4f44b14.png)

DCOR40: Same texture misaligned on a switch.
![image](https://user-images.githubusercontent.com/57696110/80800177-09fa9980-8bd3-11ea-88e1-ed3929bbac7d.png)

_Dev note: Fixed in commit d5ca7f5_

**Comment by Fluffx** [comment]
DCOR47: The secret exit takes to DCOR63, which is intended. Both exits there take to DCOR64, which is the 2nd secret exit, then the DCOR64 exit goes to DCOR65, but it's supposed to be DCOR48.

In other words, DCOR47's secret exit ignores map 48 - 62.

_Dev note: Fixed in commit ee974a2_

**Comment by Fluffx** [comment]
Some more misaligned textures:

**DCOR48**
![DCOR48](https://user-images.githubusercontent.com/26505960/80933196-f4e45d00-8dc2-11ea-8b9a-9b3c57eb0c0a.png)

**DCOR58**
![DCOR58](https://user-images.githubusercontent.com/26505960/80933206-02014c00-8dc3-11ea-9ed3-20e42f6c0bf9.png)
![DCOR58-2](https://user-images.githubusercontent.com/26505960/80933209-0594d300-8dc3-11ea-84ab-217d0a76e38c.png)

_Dev note: Fixed in commit d5ca7f5_

**Comment by Tribeam** [comment]
Wrong switch texture fixed in commit d5ca7f5

**Comment by Tribeam** [comment]
Missing BARONDED texture fixed in commit 3a79797
